"""Generator: sandbox.init -> a ``bootstrap.sh`` init script.

The script is injected into the stock ``debian`` VM via microsandbox's
``--copy-file`` rootfs-patch and run once with ``msb exec``. It installs node,
bun, python, loki-mode, skillkit and any provider CLIs requested by the manifest.

This is a pure function over ``PlatformManifest`` -> text, so it is fully
testable without a VM.
"""

from __future__ import annotations

from microcode.generators.base import GeneratedArtifact, GenerationResult
from microcode.manifest import PlatformManifest


def _quote(item: str) -> str:
    """Single-quote an apt/npm token for safe shell inclusion."""
    return "'" + item.replace("'", "'\"'\"'") + "'"


def _provider_cli_install_lines(provider_clis: list[str]) -> list[str]:
    """Emit install lines for loki provider CLIs (claude/codex/cline/aider)."""
    lines: list[str] = []
    cli_map = {
        "claude": "npm install -g @anthropic-ai/claude-code",
        # codex/codex CLI is installed via npm; name kept generic.
        "codex": "npm install -g @openai/codex",
        "cline": "npm install -g @anthropic-ai/cline",
        "aider": "pip install --break-system-packages aider-chat",
    }
    for cli in provider_clis:
        cmd = cli_map.get(cli)
        if cmd:
            lines.append(f"echo '[bootstrap] installing provider CLI: {cli}'")
            lines.append(cmd)
    return lines


def _render_bootstrap(m: PlatformManifest) -> str:
    init = m.sandbox.init.packages
    snap = m.sandbox.init.snapshot

    apt_pkgs = init.apt
    npm_pkgs = init.npm_global

    lines: list[str] = [
        "#!/usr/bin/env bash",
        "# Generated by microcode. Installs the runtime inside the debian VM.",
        "# Re-runnable: safe to execute multiple times.",
        "set -euo pipefail",
        "",
        "export DEBIAN_FRONTEND=noninteractive",
        "export PATH=\"$HOME/.bun/bin:$PATH\"",
        "",
        "echo '[bootstrap] apt-get update + install'",
        "apt-get update -qq",
    ]

    # apt packages
    if apt_pkgs:
        quoted = " ".join(_quote(p) for p in apt_pkgs)
        lines.append(f"apt-get install -y -qq {quoted}")

    # node via NodeSource
    lines += [
        "",
        f"echo '[bootstrap] node {init.node_version} via NodeSource'",
        f"curl -fsSL https://deb.nodesource.com/setup_{init.node_version}.x | bash -",
        "apt-get install -y -qq nodejs",
    ]

    # bun
    if init.bun:
        lines += [
            "",
            "echo '[bootstrap] bun'",
            "curl -fsSL https://bun.sh/install | bash",
            "grep -q 'HOME/.bun/bin' \"$HOME/.bashrc\" || "
            "echo 'export PATH=\"$HOME/.bun/bin:$PATH\"' >> \"$HOME/.bashrc\"",
        ]

    # python pip hint (python3 may already be installed via apt above)
    lines += [
        "",
        "echo '[bootstrap] ensure pip / venv'",
        "python3 -m ensurepip --upgrade || true",
    ]

    # npm global packages (loki-mode, skillkit, ...)
    if npm_pkgs:
        lines.append("")
        lines.append("echo '[bootstrap] npm global packages'")
        for pkg in npm_pkgs:
            lines.append(f"npm install -g {_quote(pkg)}")

    # provider CLIs
    prov_lines = _provider_cli_install_lines(m.loki.provider_clis)
    if prov_lines:
        lines.append("")
        lines.append("echo '[bootstrap] loki provider CLIs'")
        lines.extend(prov_lines)

    # user-supplied tail
    if init.extra_shell.strip():
        lines.append("")
        lines.append("echo '[bootstrap] extra_shell'")
        lines.append(init.extra_shell.strip())

    # snapshot hint (informational; actual snapshot taken by the runner)
    if snap.enabled:
        lines.append("")
        lines.append(
            f"echo '[bootstrap] done. runner will snapshot as {snap.name}.'"
        )
    else:
        lines.append("")
        lines.append("echo '[bootstrap] done.'")

    return "\n".join(lines) + "\n"


def generate_bootstrap(m: PlatformManifest) -> GenerationResult:
    return GenerationResult(
        artifacts=[GeneratedArtifact(name="bootstrap.sh", content=_render_bootstrap(m))],
        notes=["chmod 0755 before copying into the VM (mode is inherited via --copy-file)"],
    )
