// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"
	"log/slog"

	"github.com/loki/todoservice/internal/transport/srvctx"
)

func withMethodLogger(ctx context.Context, contract string, method string) context.Context {
	log := srvctx.GetLogger(ctx)
	if log == nil {
		log = slog.Default()
	}
	return srvctx.WithCtx[*slog.Logger](ctx, log.With("contract", contract, "method", method))
}
