// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import "log/slog"

type withErrorCode interface {
	Code() int
}

type withRedirect interface {
	RedirectTo() string
}

type errValidation struct {
	TrKey string `json:"trKey"`
	Data  string `json:"data,omitempty"`
	code  int
}

func (e *errValidation) Error() string {
	return e.Data
}
func (e *errValidation) Code() int {
	return e.code
}

func errBadRequestData(data string) *errValidation {
	return &errValidation{
		Data:  data,
		TrKey: "badRequest",
		code:  400,
	}
}

func ExitOnError(log *slog.Logger, err error, msg string) {
	if err != nil {
		log.Error(msg, slog.Any("error", err.Error()))
		panic(err)
	}
}
