// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"log/slog"
	"runtime/debug"
	"strings"

	"github.com/gofiber/fiber/v2"
	"github.com/loki/todoservice/internal/transport/srvctx"
)

func ensureBodyReader(r io.Reader) io.Reader {
	if r == nil {
		return bytes.NewReader(nil)
	}
	return r
}

const logLevelHeader = "X-Log-Level"

type levelHandler struct {
	handler slog.Handler
	level   *slog.LevelVar
}

func (h *levelHandler) Enabled(ctx context.Context, level slog.Level) bool {
	return level >= h.level.Level() && h.handler.Enabled(ctx, level)
}

func (h *levelHandler) Handle(ctx context.Context, r slog.Record) error {
	return h.handler.Handle(ctx, r)
}

func (h *levelHandler) WithAttrs(attrs []slog.Attr) slog.Handler {
	return &levelHandler{
		handler: h.handler.WithAttrs(attrs),
		level:   h.level,
	}
}

func (h *levelHandler) WithGroup(name string) slog.Handler {
	return &levelHandler{
		handler: h.handler.WithGroup(name),
		level:   h.level,
	}
}

func (srv *Server) requestLogger(ctx context.Context) (log *slog.Logger) {
	log = srv.log.With("clientID", srvctx.GetClientID(ctx))
	return log
}

func (srv *Server) setLogger(ftx *fiber.Ctx) error {
	ctx := ftx.UserContext()
	if srvctx.FromCtx[*slog.Logger](ctx) != nil {
		return ftx.Next()
	}
	levelName := strings.Clone(string(ftx.Request().Header.Peek(logLevelHeader)))
	if levelName == "" {
		ftx.SetUserContext(srvctx.WithCtx[*slog.Logger](ctx, srv.requestLogger(ctx)))
		return ftx.Next()
	}
	var level slog.Level
	switch levelName {
	case "debug", "DEBUG":
		level = slog.LevelDebug
	case "info", "INFO":
		level = slog.LevelInfo
	case "warn", "WARN":
		level = slog.LevelWarn
	case "error", "ERROR":
		level = slog.LevelError
	default:
		ftx.SetUserContext(srvctx.WithCtx[*slog.Logger](ctx, srv.requestLogger(ctx)))
		return ftx.Next()
	}
	levelVar := new(slog.LevelVar)
	levelVar.Set(level)
	log := srv.requestLogger(ctx)
	baseHandler := log.Handler()
	levelLogger := slog.New(&levelHandler{
		handler: baseHandler,
		level:   levelVar,
	})
	ftx.SetUserContext(srvctx.WithCtx[*slog.Logger](ctx, levelLogger))
	return ftx.Next()
}

func recoverHandler(ftx *fiber.Ctx) error {
	path := strings.Clone(ftx.Path())
	method := strings.Clone(ftx.Method())
	originalURL := strings.Clone(ftx.OriginalURL())
	defer func() {
		if r := recover(); r != nil {
			err, ok := r.(error)
			if !ok {
				err = fmt.Errorf("%v", r)
			}
			if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
				clientID := srvctx.GetClientID(ftx.UserContext())
				server.metrics.PanicsTotal.WithLabelValues(path, method, clientID).Inc()
			}
			if logger := srvctx.FromCtx[*slog.Logger](ftx.UserContext()); logger != nil {
				logger.Error("panic occurred", slog.Any("error", fmt.Errorf("recover: %w", err)), slog.String("method", method), slog.String("path", originalURL), slog.String("stack", string(debug.Stack())))
			}
			ftx.Status(fiber.StatusInternalServerError)
			_ = ftx.JSON(map[string]string{"message": "internal server error"})
		}
	}()
	return ftx.Next()
}
