// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"

	"github.com/gofiber/fiber/v2"
	"github.com/loki/todoservice/internal/transport/srvctx"
)

type Header struct {
	SpanKey       string
	SpanValue     any
	RequestKey    string
	RequestValue  any
	ResponseKey   string
	ResponseValue any
	LogKey        string
	LogValue      any
}

type HeaderHandler func(value string) Header

func (srv *Server) headersHandler(ftx *fiber.Ctx) error {

	if len(srv.headerHandlers) == 0 {
		return ftx.Next()
	}

	req := ftx.Request()
	resp := ftx.Response()
	ctx := ftx.UserContext()
	logger := srvctx.FromCtx[*slog.Logger](ctx)

	var logAttrs []slog.Attr
	updatedCtx := ctx
	for headerName, handler := range srv.headerHandlers {
		value := req.Header.Peek(headerName)
		header := handler(strings.Clone(string(value)))
		if header.RequestValue != nil {
			req.Header.Set(header.RequestKey, headerValue(header.RequestValue))
		}
		if header.ResponseValue != nil {
			resp.Header.Set(header.ResponseKey, headerValue(header.ResponseValue))
		}
		if header.LogValue != nil {
			if logger != nil {
				logAttrs = append(logAttrs, slog.Any(header.LogKey, header.LogValue))
			}
		}
	}
	if len(logAttrs) > 0 {
		if logger != nil {
			args := make([]any, 0, len(logAttrs))
			for _, attr := range logAttrs {
				args = append(args, attr)
			}
			requestLogger := logger.With(args...)
			updatedCtx = srvctx.WithCtx[*slog.Logger](updatedCtx, requestLogger)
		}
	}
	if updatedCtx != ctx {
		ftx.SetUserContext(updatedCtx)
	}
	return ftx.Next()
}

func headerValue(src any) (value string) {

	if v, ok := src.(string); ok {
		return v
	}
	if v, ok := src.(iHeaderValue); ok {
		return v.Header()
	}
	if v, ok := src.(fmt.Stringer); ok {
		return v.String()
	}
	bytes, err := json.Marshal(src)
	if err != nil {
		return fmt.Sprint(src)
	}
	return string(bytes)
}

type iHeaderValue interface {
	Header() string
}
