// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"log/slog"
	"os"
	"sync"

	"github.com/gofiber/adaptor/v2"
	"github.com/gofiber/fiber/v2"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/collectors"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

const (
	metricSuccessTrue    = "true"
	metricSuccessFalse   = "false"
	metricErrCodeSuccess = "0"
)

type Metrics struct {
	VersionGauge        *prometheus.GaugeVec
	EntryRequestsTotal  *prometheus.CounterVec
	PanicsTotal         *prometheus.CounterVec
	ErrorResponsesTotal *prometheus.CounterVec
	RequestsInFlight    *prometheus.GaugeVec
	RequestDuration     *prometheus.HistogramVec
	BatchSize           *prometheus.HistogramVec
	RequestCount        *prometheus.CounterVec
	RequestLatency      *prometheus.HistogramVec
}

var registerGoCollectorOnce sync.Once

func NewMetrics() *Metrics {

	registerGoCollectorOnce.Do(func() {
		_ = prometheus.Register(collectors.NewGoCollector())
	})
	hostname, _ := os.Hostname()
	m := &Metrics{
		BatchSize: promauto.NewHistogramVec(prometheus.HistogramOpts{
			Buckets:   []float64{1, 5, 10, 25, 50, 100, 200, 400, 600, 800, 1000},
			Help:      "Distribution of batch size",
			Name:      "batch_size",
			Namespace: "service",
		}, []string{"protocol", "endpoint", "client_id"}),
		EntryRequestsTotal: promauto.NewCounterVec(prometheus.CounterOpts{
			Help:      "Incoming HTTP requests to all endpoints",
			Name:      "entry_requests_total",
			Namespace: "service",
		}, []string{"protocol", "result", "client_id"}),
		ErrorResponsesTotal: promauto.NewCounterVec(prometheus.CounterOpts{
			Help:      "Error responses sent to clients",
			Name:      "error_responses_total",
			Namespace: "service",
		}, []string{"protocol", "code", "client_id"}),
		PanicsTotal: promauto.NewCounterVec(prometheus.CounterOpts{
			Help:      "Number of panics caught",
			Name:      "panics_total",
			Namespace: "service",
		}, []string{"path", "method", "client_id"}),
		RequestCount: promauto.NewCounterVec(prometheus.CounterOpts{
			Help:      "Number of method calls processed",
			Name:      "requests_count",
			Namespace: "service",
		}, []string{"service", "method", "success", "errCode", "client_id"}),
		RequestDuration: promauto.NewHistogramVec(prometheus.HistogramOpts{
			Buckets:   []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10},
			Help:      "Full HTTP request duration in seconds",
			Name:      "request_duration_seconds",
			Namespace: "service",
		}, []string{"client_id"}),
		RequestLatency: promauto.NewHistogramVec(prometheus.HistogramOpts{
			Buckets:   []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10},
			Help:      "Method execution latency in seconds",
			Name:      "requests_latency_seconds",
			Namespace: "service",
		}, []string{"service", "method", "success", "errCode", "client_id"}),
		RequestsInFlight: promauto.NewGaugeVec(prometheus.GaugeOpts{
			Help:      "Current number of HTTP requests being processed",
			Name:      "requests_in_flight",
			Namespace: "service",
		}, []string{"path", "client_id"}),
		VersionGauge: promauto.NewGaugeVec(prometheus.GaugeOpts{
			Help:      "Versions of service parts",
			Name:      "count",
			Namespace: "service",
			Subsystem: "versions",
		}, []string{"part", "version", "hostname"}),
	}
	m.VersionGauge.WithLabelValues("astg", VersionASTg, hostname).Set(1)
	return m
}
func (srv *Server) ServeMetrics(log *slog.Logger, path string, address string, regs ...*prometheus.Registry) {
	srv.srvMetrics = fiber.New(fiber.Config{DisableStartupMessage: true})
	gatherers := []prometheus.Gatherer{prometheus.DefaultGatherer}
	for _, r := range regs {
		if r != nil {
			gatherers = append(gatherers, r)
		}
	}
	handler := promhttp.HandlerFor(prometheus.Gatherers(gatherers), promhttp.HandlerOpts{})
	srv.srvMetrics.All(path, adaptor.HTTPHandler(handler))
	go func() {
		err := srv.srvMetrics.Listen(address)
		ExitOnError(log, err, "serve metrics on "+address)
	}()
}
