// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
	"github.com/loki/todoservice/contracts"
)

type ServiceRoute interface {
	SetRoutes(route *fiber.App)
}

type Option func(srv *Server)
type Handler = fiber.Handler
type ErrorHandler func(err error) error

func Service(svc ServiceRoute) Option {
	return func(srv *Server) {
		if srv.srvHTTP != nil {
			svc.SetRoutes(srv.Fiber())
		}
	}
}

func PersonalProfileService(svc contracts.PersonalProfileService) Option {
	return func(srv *Server) {
		if srv.srvHTTP != nil {
			httpSvc := newPersonalProfileService(svc)
			srv.httpPersonalProfileService = httpSvc
			httpSvc.SetRoutes(srv.Fiber())
		}
	}
}

func TodoService(svc contracts.TodoService) Option {
	return func(srv *Server) {
		if srv.srvHTTP != nil {
			httpSvc := newTodoService(svc)
			srv.httpTodoService = httpSvc
			httpSvc.SetRoutes(srv.Fiber())
		}
	}
}

func SetFiberCfg(cfg fiber.Config) Option {
	return func(srv *Server) {
		srv.config = cfg
		srv.config.StreamRequestBody = true
		srv.config.DisableStartupMessage = true
		srv.config.DisablePreParseMultipartForm = true
	}
}

func SetReadBufferSize(size int) Option {
	return func(srv *Server) {
		srv.config.ReadBufferSize = size
	}
}

func SetWriteBufferSize(size int) Option {
	return func(srv *Server) {
		srv.config.WriteBufferSize = size
	}
}

func MaxBodySize(size int) Option {
	return func(srv *Server) {
		srv.config.BodyLimit = size
	}
}

func ReadTimeout(timeout time.Duration) Option {
	return func(srv *Server) {
		srv.config.ReadTimeout = timeout
	}
}

func WriteTimeout(timeout time.Duration) Option {
	return func(srv *Server) {
		srv.config.WriteTimeout = timeout
	}
}

func WithRequestID(headerName string) Option {
	return func(srv *Server) {
		srv.headerHandlers[headerName] = func(value string) Header {
			if value == "" {
				value = uuid.New().String()
			}
			return Header{

				LogKey:        "requestID",
				LogValue:      value,
				ResponseKey:   headerName,
				ResponseValue: value,
				SpanKey:       "requestID",
				SpanValue:     value,
			}
		}
	}
}

func WithHeader(headerName string, handler HeaderHandler) Option {
	return func(srv *Server) {
		srv.headerHandlers[headerName] = handler
	}
}

func Use(args ...any) Option {
	return func(srv *Server) {
		if srv.srvHTTP != nil {
			srv.srvHTTP.Use(args...)
		}
	}
}

func UserService(svc contracts.UserService) Option {
	return func(srv *Server) {
		if srv.srvHTTP != nil {
			httpSvc := newUserService(svc)
			srv.httpUserService = httpSvc
			httpSvc.SetRoutes(srv.Fiber())
		}
	}
}
