// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import "github.com/loki/todoservice/contracts/dto"

type requestPersonalProfileServiceCreate struct {
	Name string `json:"name"`
}

type responsePersonalProfileServiceCreate struct {
	dto.PersonalProfile `json:",inline"`
}

type requestPersonalProfileServiceList struct{}

type responsePersonalProfileServiceList struct {
	Profiles []dto.PersonalProfile `json:"profiles"`
}

type requestPersonalProfileServiceGet struct {
	Id int64 `json:"-"`
}

type responsePersonalProfileServiceGet struct {
	dto.PersonalProfile `json:",inline"`
}

type requestPersonalProfileServiceUpdate struct {
	Id   int64   `json:"-"`
	Name *string `json:"name"`
}

type responsePersonalProfileServiceUpdate struct {
	dto.PersonalProfile `json:",inline"`
}

type requestPersonalProfileServiceDelete struct {
	Id int64 `json:"-"`
}

type responsePersonalProfileServiceDelete struct{}
