// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/loki/todoservice/contracts"
	"github.com/loki/todoservice/contracts/dto"
)

type PersonalProfileServiceCreate func(ctx context.Context, name string) (profile dto.PersonalProfile, err error)
type PersonalProfileServiceList func(ctx context.Context) (profiles []dto.PersonalProfile, err error)
type PersonalProfileServiceGet func(ctx context.Context, id int64) (profile dto.PersonalProfile, err error)
type PersonalProfileServiceUpdate func(ctx context.Context, id int64, name *string) (profile dto.PersonalProfile, err error)
type PersonalProfileServiceDelete func(ctx context.Context, id int64) (err error)

type MiddlewarePersonalProfileService func(next contracts.PersonalProfileService) contracts.PersonalProfileService

type MiddlewarePersonalProfileServiceCreate func(next PersonalProfileServiceCreate) PersonalProfileServiceCreate
type MiddlewarePersonalProfileServiceList func(next PersonalProfileServiceList) PersonalProfileServiceList
type MiddlewarePersonalProfileServiceGet func(next PersonalProfileServiceGet) PersonalProfileServiceGet
type MiddlewarePersonalProfileServiceUpdate func(next PersonalProfileServiceUpdate) PersonalProfileServiceUpdate
type MiddlewarePersonalProfileServiceDelete func(next PersonalProfileServiceDelete) PersonalProfileServiceDelete
