// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/fiber/v2"
	"github.com/loki/todoservice/contracts"
)

type httpPersonalProfileService struct {
	errorHandler ErrorHandler
	svc          *serverPersonalProfileService
	base         contracts.PersonalProfileService
}

func newPersonalProfileService(svcPersonalProfileService contracts.PersonalProfileService) (srv *httpPersonalProfileService) {

	srv = &httpPersonalProfileService{
		base: svcPersonalProfileService,
		svc:  newServerPersonalProfileService(svcPersonalProfileService),
	}
	return
}

func (http *httpPersonalProfileService) Service() *serverPersonalProfileService {
	return http.svc
}

func (http *httpPersonalProfileService) WithErrorHandler(handler ErrorHandler) *httpPersonalProfileService {
	http.errorHandler = handler
	return http
}

func (http *httpPersonalProfileService) WithRedirect() *httpPersonalProfileService {
	return http
}

func (http *httpPersonalProfileService) SetRoutes(route *fiber.App) {
	route.Post("/personal-profile", http.serveCreate)
	route.Get("/personal-profile", http.serveList)
	route.Get("/personal-profile/:id", http.serveGet)
	route.Patch("/personal-profile/:id", http.serveUpdate)
	route.Delete("/personal-profile/:id", http.serveDelete)
}
