// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/loki/todoservice/contracts"
	"github.com/loki/todoservice/contracts/dto"
)

type serverPersonalProfileService struct {
	svc    contracts.PersonalProfileService
	create PersonalProfileServiceCreate
	list   PersonalProfileServiceList
	get    PersonalProfileServiceGet
	update PersonalProfileServiceUpdate
	delete PersonalProfileServiceDelete
}

type MiddlewareSetPersonalProfileService interface {
	Wrap(m MiddlewarePersonalProfileService)
	WrapCreate(m MiddlewarePersonalProfileServiceCreate)
	WrapList(m MiddlewarePersonalProfileServiceList)
	WrapGet(m MiddlewarePersonalProfileServiceGet)
	WrapUpdate(m MiddlewarePersonalProfileServiceUpdate)
	WrapDelete(m MiddlewarePersonalProfileServiceDelete)
}

func newServerPersonalProfileService(svc contracts.PersonalProfileService) *serverPersonalProfileService {
	return &serverPersonalProfileService{
		create: svc.Create,
		delete: svc.Delete,
		get:    svc.Get,
		list:   svc.List,
		svc:    svc,
		update: svc.Update,
	}
}

func (srv *serverPersonalProfileService) Wrap(m MiddlewarePersonalProfileService) {
	srv.svc = m(srv.svc)
	srv.create = srv.svc.Create
	srv.list = srv.svc.List
	srv.get = srv.svc.Get
	srv.update = srv.svc.Update
	srv.delete = srv.svc.Delete
}

func (srv *serverPersonalProfileService) Create(ctx context.Context, name string) (profile dto.PersonalProfile, err error) {
	return srv.create(ctx, name)
}

func (srv *serverPersonalProfileService) List(ctx context.Context) (profiles []dto.PersonalProfile, err error) {
	return srv.list(ctx)
}

func (srv *serverPersonalProfileService) Get(ctx context.Context, id int64) (profile dto.PersonalProfile, err error) {
	return srv.get(ctx, id)
}

func (srv *serverPersonalProfileService) Update(ctx context.Context, id int64, name *string) (profile dto.PersonalProfile, err error) {
	return srv.update(ctx, id, name)
}

func (srv *serverPersonalProfileService) Delete(ctx context.Context, id int64) (err error) {
	return srv.delete(ctx, id)
}

func (srv *serverPersonalProfileService) WrapCreate(m MiddlewarePersonalProfileServiceCreate) {
	srv.create = m(srv.create)
}

func (srv *serverPersonalProfileService) WrapList(m MiddlewarePersonalProfileServiceList) {
	srv.list = m(srv.list)
}

func (srv *serverPersonalProfileService) WrapGet(m MiddlewarePersonalProfileServiceGet) {
	srv.get = m(srv.get)
}

func (srv *serverPersonalProfileService) WrapUpdate(m MiddlewarePersonalProfileServiceUpdate) {
	srv.update = m(srv.update)
}

func (srv *serverPersonalProfileService) WrapDelete(m MiddlewarePersonalProfileServiceDelete) {
	srv.delete = m(srv.delete)
}
