// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/gofiber/fiber/v2"
	"github.com/loki/todoservice/internal/transport/srvctx"
)

func (http *httpPersonalProfileService) create(ctx context.Context, request requestPersonalProfileServiceCreate) (response responsePersonalProfileServiceCreate, err error) {

	ctx = withMethodLogger(ctx, "personalProfileService", "create")

	if response.PersonalProfile, err = http.svc.Create(ctx, request.Name); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPersonalProfileService) serveCreate(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestPersonalProfileServiceCreate
	ftx.Response().SetStatusCode(201)
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	var response responsePersonalProfileServiceCreate
	if response, err = http.create(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response.PersonalProfile)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpPersonalProfileService) list(ctx context.Context, request requestPersonalProfileServiceList) (response responsePersonalProfileServiceList, err error) {

	ctx = withMethodLogger(ctx, "personalProfileService", "list")

	if response.Profiles, err = http.svc.List(ctx); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPersonalProfileService) serveList(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestPersonalProfileServiceList

	var response responsePersonalProfileServiceList
	if response, err = http.list(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpPersonalProfileService) get(ctx context.Context, request requestPersonalProfileServiceGet) (response responsePersonalProfileServiceGet, err error) {

	ctx = withMethodLogger(ctx, "personalProfileService", "get")

	if response.PersonalProfile, err = http.svc.Get(ctx, request.Id); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPersonalProfileService) serveGet(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestPersonalProfileServiceGet

	if _id_ := ftx.Params("id"); _id_ != "" {
		var id int64
		if id, err = strconv.ParseInt(_id_, 10, 64); err != nil {
			ftx.Status(fiber.StatusBadRequest)
			return sendResponse(ftx, "path arguments could not be decoded: "+err.Error())
		}
		request.Id = id
	}

	var response responsePersonalProfileServiceGet
	if response, err = http.get(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response.PersonalProfile)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpPersonalProfileService) update(ctx context.Context, request requestPersonalProfileServiceUpdate) (response responsePersonalProfileServiceUpdate, err error) {

	ctx = withMethodLogger(ctx, "personalProfileService", "update")

	if response.PersonalProfile, err = http.svc.Update(ctx, request.Id, request.Name); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPersonalProfileService) serveUpdate(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestPersonalProfileServiceUpdate
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _id_ := ftx.Params("id"); _id_ != "" {
		var id int64
		if id, err = strconv.ParseInt(_id_, 10, 64); err != nil {
			ftx.Status(fiber.StatusBadRequest)
			return sendResponse(ftx, "path arguments could not be decoded: "+err.Error())
		}
		request.Id = id
	}

	var response responsePersonalProfileServiceUpdate
	if response, err = http.update(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response.PersonalProfile)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpPersonalProfileService) delete(ctx context.Context, request requestPersonalProfileServiceDelete) (response responsePersonalProfileServiceDelete, err error) {

	ctx = withMethodLogger(ctx, "personalProfileService", "delete")

	if err = http.svc.Delete(ctx, request.Id); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPersonalProfileService) serveDelete(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestPersonalProfileServiceDelete
	ftx.Response().SetStatusCode(204)

	if _id_ := ftx.Params("id"); _id_ != "" {
		var id int64
		if id, err = strconv.ParseInt(_id_, 10, 64); err != nil {
			ftx.Status(fiber.StatusBadRequest)
			return sendResponse(ftx, "path arguments could not be decoded: "+err.Error())
		}
		request.Id = id
	}

	var response responsePersonalProfileServiceDelete
	if response, err = http.delete(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
