// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"encoding/json"
	"log/slog"
	"strconv"
	"strings"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/loki/todoservice/internal/transport/srvctx"
)

type Server struct {
	log *slog.Logger

	config fiber.Config

	srvHTTP    *fiber.App
	srvMetrics *fiber.App

	metrics *Metrics

	httpTodoService *httpTodoService

	headerHandlers map[string]HeaderHandler
}

const defaultShutdownTimeout = 30 * time.Second

const defaultBodyLimit = 8 * 1024 * 1024
const defaultReadBufferSize = 4096
const defaultWriteBufferSize = 4096
const defaultReadTimeout = 30 * time.Second
const defaultWriteTimeout = 30 * time.Second
const defaultSSEHeartbeat = 15 * time.Second
const defaultIdleTimeout = 120 * time.Second
const defaultConcurrency = 256 * 1024
const contentTypeJson = "application/json"

type HealthServer struct {
	srv          *fiber.App
	responseBody []byte
}

func (hs *HealthServer) Stop() {
	if hs.srv != nil {
		_ = hs.srv.ShutdownWithTimeout(defaultShutdownTimeout)
	}
}

func New(log *slog.Logger, options ...Option) (srv *Server) {

	srv = &Server{
		config: fiber.Config{
			BodyLimit:                    defaultBodyLimit,
			Concurrency:                  defaultConcurrency,
			DisablePreParseMultipartForm: true,
			DisableStartupMessage:        true,
			IdleTimeout:                  defaultIdleTimeout,
			ReadBufferSize:               defaultReadBufferSize,
			ReadTimeout:                  defaultReadTimeout,
			StreamRequestBody:            true,
			WriteBufferSize:              defaultWriteBufferSize,
			WriteTimeout:                 defaultWriteTimeout,
		},
		headerHandlers: make(map[string]HeaderHandler),
		log:            log,
	}

	var configOptions []Option
	var serviceOptions []Option

	for _, option := range options {
		if doesNotRequireHTTP(option) {
			serviceOptions = append(serviceOptions, option)
		} else {
			configOptions = append(configOptions, option)
		}
	}

	for _, option := range configOptions {
		option(srv)
	}

	srv.srvHTTP = fiber.New(srv.config)
	srv.srvHTTP.Use(func(ftx *fiber.Ctx) error {
		ftx.Locals("server", srv)
		return recoverHandler(ftx)
	})
	srv.srvHTTP.Use(srv.clientIDMiddleware)
	srv.srvHTTP.Use(srv.inFlightMiddleware)
	srv.srvHTTP.Use(srv.requestDurationMiddleware)
	srv.srvHTTP.Use(srv.setLogger)
	srv.srvHTTP.Use(srv.headersHandler)
	for _, option := range serviceOptions {
		option(srv)
	}

	return
}

func doesNotRequireHTTP(option Option) bool {
	testSrv := &Server{
		headerHandlers: make(map[string]HeaderHandler),
	}
	option(testSrv)
	noHTTPService := testSrv.srvHTTP == nil
	noHTTPService = noHTTPService && testSrv.httpTodoService == nil
	return noHTTPService
}

func (srv *Server) Fiber() *fiber.App {
	return srv.srvHTTP
}

func (srv *Server) WithLog() *Server {
	return srv
}

func ServeHealth(log *slog.Logger, path string, address string, response any) *HealthServer {
	var err error
	var responseBody []byte
	if response != nil {
		responseBody, err = json.Marshal(response)
		if err != nil {
			log.Error("failed to marshal health response", slog.Any("error", err))
			responseBody = []byte("{\"status\":\"error\",\"message\":\"health check misconfigured\"}")
		}
	} else {
		responseBody = []byte("\"ok\"")
	}
	srv := fiber.New(fiber.Config{
		DisablePreParseMultipartForm: true,
		DisableStartupMessage:        true,
		IdleTimeout:                  defaultIdleTimeout,
		ReadTimeout:                  defaultReadTimeout,
		WriteTimeout:                 defaultWriteTimeout,
	})
	srv.Get(path, func(ftx *fiber.Ctx) (err error) {
		ftx.Response().Header.SetContentType(contentTypeJson)
		ftx.Response().Header.SetContentLength(len(responseBody))
		_, err = ftx.Write(responseBody)
		return
	})
	go func() {
		err = srv.Listen(address)
		ExitOnError(log, err, "serve health on "+address)
	}()
	return &HealthServer{
		responseBody: responseBody,
		srv:          srv,
	}
}

func sendResponse(ftx *fiber.Ctx, resp any) (err error) {
	ftx.Response().Header.SetContentType("application/json")
	if err = json.NewEncoder(ftx.Response().BodyWriter()).Encode(resp); err != nil {
		if logger := srvctx.FromCtx[*slog.Logger](ftx.UserContext()); logger != nil {
			logger.Error("response marshal error", slog.Any("error", err))
		}
		ftx.Status(fiber.StatusInternalServerError)
		return err
	}
	return err
}

func sendHTTPError(ftx *fiber.Ctx, statusCode int, message string) (err error) {
	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("json-rpc", strconv.Itoa(statusCode), clientID).Inc()
	}
	ftx.Response().Header.SetContentType("text/plain")
	ftx.Status(statusCode)
	_, err = ftx.WriteString(message)
	return err
}

func (srv *Server) Shutdown() (err error) {
	if srv.srvHTTP != nil {
		if err = srv.srvHTTP.ShutdownWithTimeout(defaultShutdownTimeout); err != nil {
			return err
		}
	}
	if srv.srvMetrics != nil {
		if err = srv.srvMetrics.ShutdownWithTimeout(defaultShutdownTimeout); err != nil {
			return err
		}
	}
	return
}

func (srv *Server) clientIDMiddleware(ftx *fiber.Ctx) error {
	clientID := strings.Clone(strings.TrimSpace(ftx.Get("X-Client-Id")))
	if clientID == "" {
		clientID = "unknown"
	}
	ctx := ftx.UserContext()
	ftx.SetUserContext(srvctx.WithCtx(ctx, srvctx.ClientID(clientID)))
	return ftx.Next()
}

func (srv *Server) inFlightMiddleware(ftx *fiber.Ctx) error {
	if srv.metrics != nil {
		path := strings.Clone(ftx.Path())
		clientID := srvctx.GetClientID(ftx.UserContext())
		srv.metrics.RequestsInFlight.WithLabelValues(path, clientID).Inc()
		defer srv.metrics.RequestsInFlight.WithLabelValues(path, clientID).Dec()
	}
	return ftx.Next()
}

func (srv *Server) requestDurationMiddleware(ftx *fiber.Ctx) error {
	if srv.metrics != nil {
		start := time.Now()
		defer func() {
			clientID := srvctx.GetClientID(ftx.UserContext())
			srv.metrics.RequestDuration.WithLabelValues(clientID).Observe(time.Since(start).Seconds())
		}()
	}
	return ftx.Next()
}

func (srv *Server) WithMetrics() *Server {
	if srv.metrics == nil {
		srv.metrics = NewMetrics()
	}
	if srv.httpTodoService != nil {
		srv.httpTodoService = srv.httpTodoService.WithMetrics(srv.metrics)
	}
	return srv
}

func (srv *Server) TodoService() *httpTodoService {
	return srv.httpTodoService
}
