// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/fiber/v2"
	"github.com/loki/todoservice/contracts"
)

type httpTodoService struct {
	errorHandler ErrorHandler
	svc          *serverTodoService
	base         contracts.TodoService
}

func newTodoService(svcTodoService contracts.TodoService) (srv *httpTodoService) {

	srv = &httpTodoService{
		base: svcTodoService,
		svc:  newServerTodoService(svcTodoService),
	}
	return
}

func (http *httpTodoService) Service() *serverTodoService {
	return http.svc
}

func (http *httpTodoService) WithMetrics(metrics *Metrics) *httpTodoService {
	http.svc.WithMetrics(metrics)
	return http
}

func (http *httpTodoService) WithErrorHandler(handler ErrorHandler) *httpTodoService {
	http.errorHandler = handler
	return http
}

func (http *httpTodoService) WithRedirect() *httpTodoService {
	return http
}

func (http *httpTodoService) SetRoutes(route *fiber.App) {
	route.Post("/todos", http.serveCreate)
	route.Get("/todos", http.serveList)
	route.Get("/todos/:id", http.serveGet)
	route.Patch("/todos/:id", http.serveUpdate)
	route.Delete("/todos/:id", http.serveDelete)
	route.Post("/todos/:id/toggle", http.serveToggle)
}
