// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/loki/todoservice/contracts"
	"github.com/loki/todoservice/contracts/dto"
)

type TodoServiceCreate func(ctx context.Context, lkId int64, title string, description string) (todo dto.Todo, err error)
type TodoServiceList func(ctx context.Context, lkId int64) (todos []dto.Todo, err error)
type TodoServiceGet func(ctx context.Context, lkId int64, id int64) (todo dto.Todo, err error)
type TodoServiceUpdate func(ctx context.Context, id int64, title *string, description *string, completed *bool) (todo dto.Todo, err error)
type TodoServiceDelete func(ctx context.Context, id int64) (err error)
type TodoServiceToggle func(ctx context.Context, id int64) (todo dto.Todo, err error)

type MiddlewareTodoService func(next contracts.TodoService) contracts.TodoService

type MiddlewareTodoServiceCreate func(next TodoServiceCreate) TodoServiceCreate
type MiddlewareTodoServiceList func(next TodoServiceList) TodoServiceList
type MiddlewareTodoServiceGet func(next TodoServiceGet) TodoServiceGet
type MiddlewareTodoServiceUpdate func(next TodoServiceUpdate) TodoServiceUpdate
type MiddlewareTodoServiceDelete func(next TodoServiceDelete) TodoServiceDelete
type MiddlewareTodoServiceToggle func(next TodoServiceToggle) TodoServiceToggle
