// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/loki/todoservice/contracts"
	"github.com/loki/todoservice/contracts/dto"
)

type serverTodoService struct {
	svc    contracts.TodoService
	create TodoServiceCreate
	list   TodoServiceList
	get    TodoServiceGet
	update TodoServiceUpdate
	delete TodoServiceDelete
	toggle TodoServiceToggle
}

type MiddlewareSetTodoService interface {
	Wrap(m MiddlewareTodoService)
	WrapCreate(m MiddlewareTodoServiceCreate)
	WrapList(m MiddlewareTodoServiceList)
	WrapGet(m MiddlewareTodoServiceGet)
	WrapUpdate(m MiddlewareTodoServiceUpdate)
	WrapDelete(m MiddlewareTodoServiceDelete)
	WrapToggle(m MiddlewareTodoServiceToggle)

	WithMetrics(metrics *Metrics)
}

func newServerTodoService(svc contracts.TodoService) *serverTodoService {
	return &serverTodoService{
		create: svc.Create,
		delete: svc.Delete,
		get:    svc.Get,
		list:   svc.List,
		svc:    svc,
		toggle: svc.Toggle,
		update: svc.Update,
	}
}

func (srv *serverTodoService) Wrap(m MiddlewareTodoService) {
	srv.svc = m(srv.svc)
	srv.create = srv.svc.Create
	srv.list = srv.svc.List
	srv.get = srv.svc.Get
	srv.update = srv.svc.Update
	srv.delete = srv.svc.Delete
	srv.toggle = srv.svc.Toggle
}

func (srv *serverTodoService) Create(ctx context.Context, title string, description string) (todo dto.Todo, err error) {
	return srv.create(ctx, title, description)
}

func (srv *serverTodoService) List(ctx context.Context) (todos []dto.Todo, err error) {
	return srv.list(ctx)
}

func (srv *serverTodoService) Get(ctx context.Context, id int64) (todo dto.Todo, err error) {
	return srv.get(ctx, id)
}

func (srv *serverTodoService) Update(ctx context.Context, id int64, title *string, description *string, completed *bool) (todo dto.Todo, err error) {
	return srv.update(ctx, id, title, description, completed)
}

func (srv *serverTodoService) Delete(ctx context.Context, id int64) (err error) {
	return srv.delete(ctx, id)
}

func (srv *serverTodoService) Toggle(ctx context.Context, id int64) (todo dto.Todo, err error) {
	return srv.toggle(ctx, id)
}

func (srv *serverTodoService) WrapCreate(m MiddlewareTodoServiceCreate) {
	srv.create = m(srv.create)
}

func (srv *serverTodoService) WrapList(m MiddlewareTodoServiceList) {
	srv.list = m(srv.list)
}

func (srv *serverTodoService) WrapGet(m MiddlewareTodoServiceGet) {
	srv.get = m(srv.get)
}

func (srv *serverTodoService) WrapUpdate(m MiddlewareTodoServiceUpdate) {
	srv.update = m(srv.update)
}

func (srv *serverTodoService) WrapDelete(m MiddlewareTodoServiceDelete) {
	srv.delete = m(srv.delete)
}

func (srv *serverTodoService) WrapToggle(m MiddlewareTodoServiceToggle) {
	srv.toggle = m(srv.toggle)
}

func (srv *serverTodoService) WithMetrics(metrics *Metrics) {
	srv.Wrap(func(next contracts.TodoService) contracts.TodoService {
		return metricsMiddlewareTodoService(next, metrics)
	})
}
