// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"
	"strconv"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/loki/todoservice/contracts"
	"github.com/loki/todoservice/contracts/dto"
	"github.com/loki/todoservice/internal/transport/srvctx"
)

const (
	metricServiceTodoService = "todoService"
)
const metricMethodTodoServiceCreate = "create"
const metricMethodTodoServiceList = "list"
const metricMethodTodoServiceGet = "get"
const metricMethodTodoServiceUpdate = "update"
const metricMethodTodoServiceDelete = "delete"
const metricMethodTodoServiceToggle = "toggle"

type metricsTodoService struct {
	next    contracts.TodoService
	metrics *Metrics
}

func metricsMiddlewareTodoService(next contracts.TodoService, metrics *Metrics) contracts.TodoService {
	return &metricsTodoService{
		metrics: metrics,
		next:    next,
	}
}

func (m metricsTodoService) Create(ctx context.Context, title string, description string) (todo dto.Todo, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceCreate, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceCreate, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceCreate, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceCreate, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Create(ctx, title, description)
}

func (m metricsTodoService) List(ctx context.Context) (todos []dto.Todo, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceList, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceList, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceList, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceList, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.List(ctx)
}

func (m metricsTodoService) Get(ctx context.Context, id int64) (todo dto.Todo, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceGet, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceGet, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceGet, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceGet, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Get(ctx, id)
}

func (m metricsTodoService) Update(ctx context.Context, id int64, title *string, description *string, completed *bool) (todo dto.Todo, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceUpdate, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceUpdate, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceUpdate, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceUpdate, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Update(ctx, id, title, description, completed)
}

func (m metricsTodoService) Delete(ctx context.Context, id int64) (err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceDelete, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceDelete, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceDelete, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceDelete, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Delete(ctx, id)
}

func (m metricsTodoService) Toggle(ctx context.Context, id int64) (todo dto.Todo, err error) {

	defer func(_begin_ time.Time) {
		if m.metrics == nil {
			return
		}
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = fiber.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		clientID := srvctx.GetClientID(ctx)
		if success {
			m.metrics.RequestCount.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceToggle, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceToggle, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		} else {
			errCodeStr := strconv.Itoa(errCode)
			m.metrics.RequestCount.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceToggle, metricSuccessFalse, errCodeStr, clientID).Add(1)
			m.metrics.RequestLatency.WithLabelValues(metricServiceTodoService, metricMethodTodoServiceToggle, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin_).Seconds()))
		}
	}(time.Now())

	return m.next.Toggle(ctx, id)
}
