// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import "github.com/loki/todoservice/contracts/dto"

type requestTodoServiceCreate struct {
	LkId        int64  `json:"-"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type responseTodoServiceCreate struct {
	dto.Todo `json:",inline"`
}

type requestTodoServiceList struct {
	LkId int64 `json:"-"`
}

type responseTodoServiceList struct {
	Todos []dto.Todo `json:"todos"`
}

type requestTodoServiceGet struct {
	LkId int64 `json:"-"`
	Id   int64 `json:"-"`
}

type responseTodoServiceGet struct {
	dto.Todo `json:",inline"`
}

type requestTodoServiceUpdate struct {
	Id          int64   `json:"-"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Completed   *bool   `json:"completed"`
}

type responseTodoServiceUpdate struct {
	dto.Todo `json:",inline"`
}

type requestTodoServiceDelete struct {
	Id int64 `json:"-"`
}

type responseTodoServiceDelete struct{}

type requestTodoServiceToggle struct {
	Id int64 `json:"-"`
}

type responseTodoServiceToggle struct {
	dto.Todo `json:",inline"`
}
