// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/gofiber/fiber/v2"
	"github.com/loki/todoservice/internal/transport/srvctx"
)

func (http *httpTodoService) create(ctx context.Context, request requestTodoServiceCreate) (response responseTodoServiceCreate, err error) {

	ctx = withMethodLogger(ctx, "todoService", "create")

	if response.Todo, err = http.svc.Create(ctx, request.Title, request.Description); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTodoService) serveCreate(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTodoServiceCreate
	ftx.Response().SetStatusCode(201)
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	var response responseTodoServiceCreate
	if response, err = http.create(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response.Todo)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpTodoService) list(ctx context.Context, request requestTodoServiceList) (response responseTodoServiceList, err error) {

	ctx = withMethodLogger(ctx, "todoService", "list")

	if response.Todos, err = http.svc.List(ctx); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTodoService) serveList(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTodoServiceList

	var response responseTodoServiceList
	if response, err = http.list(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpTodoService) get(ctx context.Context, request requestTodoServiceGet) (response responseTodoServiceGet, err error) {

	ctx = withMethodLogger(ctx, "todoService", "get")

	if response.Todo, err = http.svc.Get(ctx, request.Id); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTodoService) serveGet(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTodoServiceGet

	if _id_ := ftx.Params("id"); _id_ != "" {
		var id int64
		if id, err = strconv.ParseInt(_id_, 10, 64); err != nil {
			ftx.Status(fiber.StatusBadRequest)
			return sendResponse(ftx, "path arguments could not be decoded: "+err.Error())
		}
		request.Id = id
	}

	var response responseTodoServiceGet
	if response, err = http.get(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response.Todo)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpTodoService) update(ctx context.Context, request requestTodoServiceUpdate) (response responseTodoServiceUpdate, err error) {

	ctx = withMethodLogger(ctx, "todoService", "update")

	if response.Todo, err = http.svc.Update(ctx, request.Id, request.Title, request.Description, request.Completed); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTodoService) serveUpdate(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTodoServiceUpdate
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _id_ := ftx.Params("id"); _id_ != "" {
		var id int64
		if id, err = strconv.ParseInt(_id_, 10, 64); err != nil {
			ftx.Status(fiber.StatusBadRequest)
			return sendResponse(ftx, "path arguments could not be decoded: "+err.Error())
		}
		request.Id = id
	}

	var response responseTodoServiceUpdate
	if response, err = http.update(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response.Todo)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpTodoService) delete(ctx context.Context, request requestTodoServiceDelete) (response responseTodoServiceDelete, err error) {

	ctx = withMethodLogger(ctx, "todoService", "delete")

	if err = http.svc.Delete(ctx, request.Id); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTodoService) serveDelete(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTodoServiceDelete
	ftx.Response().SetStatusCode(204)

	if _id_ := ftx.Params("id"); _id_ != "" {
		var id int64
		if id, err = strconv.ParseInt(_id_, 10, 64); err != nil {
			ftx.Status(fiber.StatusBadRequest)
			return sendResponse(ftx, "path arguments could not be decoded: "+err.Error())
		}
		request.Id = id
	}

	var response responseTodoServiceDelete
	if response, err = http.delete(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
func (http *httpTodoService) toggle(ctx context.Context, request requestTodoServiceToggle) (response responseTodoServiceToggle, err error) {

	ctx = withMethodLogger(ctx, "todoService", "toggle")

	if response.Todo, err = http.svc.Toggle(ctx, request.Id); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpTodoService) serveToggle(ftx *fiber.Ctx) (err error) {

	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestTodoServiceToggle

	if _id_ := ftx.Params("id"); _id_ != "" {
		var id int64
		if id, err = strconv.ParseInt(_id_, 10, 64); err != nil {
			ftx.Status(fiber.StatusBadRequest)
			return sendResponse(ftx, "path arguments could not be decoded: "+err.Error())
		}
		request.Id = id
	}

	var response responseTodoServiceToggle
	if response, err = http.toggle(ftx.UserContext(), request); err == nil {
		var iResponse any = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ftx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ftx, response.Todo)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
