// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/gofiber/fiber/v2"
	"github.com/loki/todoservice/internal/transport/srvctx"
)

func (http *httpUserService) register(ctx context.Context, request requestUserServiceRegister) (response responseUserServiceRegister, err error) {
	ctx = withMethodLogger(ctx, "userService", "register")
	if response.RegisterResponse, err = http.svc.Register(ctx, request.Email, request.Password); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpUserService) serveRegister(ftx *fiber.Ctx) (err error) {
	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestUserServiceRegister
	ftx.Response().SetStatusCode(201)
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}
	var response responseUserServiceRegister
	if response, err = http.register(ftx.UserContext(), request); err == nil {
		return sendResponse(ftx, response.RegisterResponse)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}

func (http *httpUserService) refresh(ctx context.Context, request requestUserServiceRefresh) (response responseUserServiceRefresh, err error) {
	ctx = withMethodLogger(ctx, "userService", "refresh")
	if response.TokenPair, err = http.svc.Refresh(ctx, request.RefreshToken); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpUserService) serveRefresh(ftx *fiber.Ctx) (err error) {
	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestUserServiceRefresh
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}
	var response responseUserServiceRefresh
	if response, err = http.refresh(ftx.UserContext(), request); err == nil {
		return sendResponse(ftx, response.TokenPair)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}

func (http *httpUserService) me(ctx context.Context, request requestUserServiceMe) (response responseUserServiceMe, err error) {
	ctx = withMethodLogger(ctx, "userService", "me")
	if response.User, err = http.svc.Me(ctx); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpUserService) serveMe(ftx *fiber.Ctx) (err error) {
	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestUserServiceMe
	var response responseUserServiceMe
	if response, err = http.me(ftx.UserContext(), request); err == nil {
		return sendResponse(ftx, response.User)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}

func (http *httpUserService) csrf(ctx context.Context, request requestUserServiceCsrf) (response responseUserServiceCsrf, err error) {
	ctx = withMethodLogger(ctx, "userService", "csrf")
	if response.CsrfResponse, err = http.svc.Csrf(ctx); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpUserService) serveCsrf(ftx *fiber.Ctx) (err error) {
	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestUserServiceCsrf
	var response responseUserServiceCsrf
	if response, err = http.csrf(ftx.UserContext(), request); err == nil {
		return sendResponse(ftx, response.CsrfResponse)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}

func (http *httpUserService) login(ctx context.Context, request requestUserServiceLogin) (response responseUserServiceLogin, err error) {
	ctx = withMethodLogger(ctx, "userService", "login")
	if response.TokenPair, err = http.svc.Login(ctx, request.Email, request.Password); err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpUserService) serveLogin(ftx *fiber.Ctx) (err error) {
	clientID := srvctx.GetClientID(ftx.UserContext())
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		defer func() {
			if err == nil {
				server.metrics.EntryRequestsTotal.WithLabelValues("rest", "ok", clientID).Inc()
			}
		}()
	}
	var request requestUserServiceLogin
	bodyStream := ensureBodyReader(ftx.Context().RequestBodyStream())
	if err = json.NewDecoder(bodyStream).Decode(&request); err != nil {
		if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
			server.metrics.ErrorResponsesTotal.WithLabelValues("rest", "400", clientID).Inc()
		}
		ftx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ftx.WriteString("request body could not be decoded: " + err.Error())
		return
	}
	var response responseUserServiceLogin
	if response, err = http.login(ftx.UserContext(), request); err == nil {
		return sendResponse(ftx, response.TokenPair)
	}
	var statusCode int
	if errCoder, ok := err.(withErrorCode); ok {
		statusCode = errCoder.Code()
		ftx.Status(statusCode)
	} else {
		statusCode = fiber.StatusInternalServerError
		ftx.Status(statusCode)
	}
	if server, ok := ftx.Locals("server").(*Server); ok && server.metrics != nil {
		server.metrics.ErrorResponsesTotal.WithLabelValues("rest", strconv.Itoa(statusCode), clientID).Inc()
	}
	return sendResponse(ftx, err)
}
