// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/loki/todoservice/contracts"
	"github.com/loki/todoservice/contracts/dto"
)

type serverUserService struct {
	svc       contracts.UserService
	register  UserServiceRegister
	login     UserServiceLogin
	refresh   UserServiceRefresh
	me        UserServiceMe
	csrf      UserServiceCsrf
}

type MiddlewareSetUserService interface {
	Wrap(m MiddlewareUserService)
	WrapRegister(m MiddlewareUserServiceRegister)
	WrapLogin(m MiddlewareUserServiceLogin)
	WrapRefresh(m MiddlewareUserServiceRefresh)
	WrapMe(m MiddlewareUserServiceMe)
	WrapCsrf(m MiddlewareUserServiceCsrf)

	WithMetrics(metrics *Metrics)
}

func newServerUserService(svc contracts.UserService) *serverUserService {
	return &serverUserService{
		svc:      svc,
		register: svc.Register,
		login:    svc.Login,
		refresh:  svc.Refresh,
		me:       svc.Me,
		csrf:     svc.Csrf,
	}
}

func (srv *serverUserService) Wrap(m MiddlewareUserService) {
	srv.svc = m(srv.svc)
	srv.register = srv.svc.Register
	srv.login = srv.svc.Login
	srv.refresh = srv.svc.Refresh
	srv.me = srv.svc.Me
	srv.csrf = srv.svc.Csrf
}

func (srv *serverUserService) Register(ctx context.Context, email string, password string) (resp dto.RegisterResponse, err error) {
	return srv.register(ctx, email, password)
}

func (srv *serverUserService) Login(ctx context.Context, email string, password string) (tokens dto.TokenPair, err error) {
	return srv.login(ctx, email, password)
}

func (srv *serverUserService) Refresh(ctx context.Context, refreshToken string) (tokens dto.TokenPair, err error) {
	return srv.refresh(ctx, refreshToken)
}

func (srv *serverUserService) Me(ctx context.Context) (user dto.User, err error) {
	return srv.me(ctx)
}

func (srv *serverUserService) Csrf(ctx context.Context) (resp dto.CsrfResponse, err error) {
	return srv.csrf(ctx)
}

func (srv *serverUserService) WrapRegister(m MiddlewareUserServiceRegister) {
	srv.register = m(srv.register)
}

func (srv *serverUserService) WrapLogin(m MiddlewareUserServiceLogin) {
	srv.login = m(srv.login)
}

func (srv *serverUserService) WrapRefresh(m MiddlewareUserServiceRefresh) {
	srv.refresh = m(srv.refresh)
}

func (srv *serverUserService) WrapMe(m MiddlewareUserServiceMe) {
	srv.me = m(srv.me)
}

func (srv *serverUserService) WrapCsrf(m MiddlewareUserServiceCsrf) {
	srv.csrf = m(srv.csrf)
}

func (srv *serverUserService) WithMetrics(metrics *Metrics) {
	srv.Wrap(func(next contracts.UserService) contracts.UserService {
		return metricsMiddlewareUserService(next, metrics)
	})
}
