// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/loki/todoservice/contracts"
	"github.com/loki/todoservice/contracts/dto"
)

type UserServiceRegister func(ctx context.Context, email string, password string) (resp dto.RegisterResponse, err error)
type UserServiceLogin func(ctx context.Context, email string, password string) (tokens dto.TokenPair, err error)
type UserServiceRefresh func(ctx context.Context, refreshToken string) (tokens dto.TokenPair, err error)
type UserServiceMe func(ctx context.Context) (user dto.User, err error)
type UserServiceCsrf func(ctx context.Context) (resp dto.CsrfResponse, err error)

type MiddlewareUserService func(next contracts.UserService) contracts.UserService

type MiddlewareUserServiceRegister func(next UserServiceRegister) UserServiceRegister
type MiddlewareUserServiceLogin func(next UserServiceLogin) UserServiceLogin
type MiddlewareUserServiceRefresh func(next UserServiceRefresh) UserServiceRefresh
type MiddlewareUserServiceMe func(next UserServiceMe) UserServiceMe
type MiddlewareUserServiceCsrf func(next UserServiceCsrf) UserServiceCsrf
