// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import "github.com/loki/todoservice/contracts/dto"

type requestUserServiceRegister struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type responseUserServiceRegister struct {
	dto.RegisterResponse `json:",inline"`
}

type requestUserServiceLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type responseUserServiceLogin struct {
	dto.TokenPair `json:",inline"`
}

type requestUserServiceRefresh struct {
	RefreshToken string `json:"refresh_token"`
}

type responseUserServiceRefresh struct {
	dto.TokenPair `json:",inline"`
}

type requestUserServiceMe struct{}

type responseUserServiceMe struct {
	dto.User `json:",inline"`
}

type requestUserServiceCsrf struct{}

type responseUserServiceCsrf struct {
	dto.CsrfResponse `json:",inline"`
}
