// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"context"
	"strconv"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/loki/todoservice/contracts"
	"github.com/loki/todoservice/contracts/dto"
	"github.com/loki/todoservice/internal/transport/srvctx"
)

const (
	metricServiceUserService       = "userService"
	metricMethodUserServiceRegister = "register"
	metricMethodUserServiceLogin    = "login"
	metricMethodUserServiceRefresh  = "refresh"
	metricMethodUserServiceMe       = "me"
	metricMethodUserServiceCsrf     = "csrf"
)

type metricsUserService struct {
	next    contracts.UserService
	metrics *Metrics
}

func metricsMiddlewareUserService(next contracts.UserService, metrics *Metrics) contracts.UserService {
	return &metricsUserService{metrics: metrics, next: next}
}

func (m *metricsUserService) record(ctx context.Context, method string, _begin time.Time, err error) {
	if m.metrics == nil {
		return
	}
	success := true
	errCode := 0
	if err != nil {
		success = false
		errCode = fiber.StatusInternalServerError
		if ec, ok := err.(withErrorCode); ok {
			errCode = ec.Code()
		}
	}
	clientID := srvctx.GetClientID(ctx)
	if success {
		m.metrics.RequestCount.WithLabelValues(metricServiceUserService, method, metricSuccessTrue, metricErrCodeSuccess, clientID).Add(1)
		m.metrics.RequestLatency.WithLabelValues(metricServiceUserService, method, metricSuccessTrue, metricErrCodeSuccess, clientID).Observe(float64(time.Since(_begin).Seconds()))
	} else {
		errCodeStr := strconv.Itoa(errCode)
		m.metrics.RequestCount.WithLabelValues(metricServiceUserService, method, metricSuccessFalse, errCodeStr, clientID).Add(1)
		m.metrics.RequestLatency.WithLabelValues(metricServiceUserService, method, metricSuccessFalse, errCodeStr, clientID).Observe(float64(time.Since(_begin).Seconds()))
	}
}

func (m *metricsUserService) Register(ctx context.Context, email string, password string) (resp dto.RegisterResponse, err error) {
	defer func(t time.Time) { m.record(ctx, metricMethodUserServiceRegister, t, err) }(time.Now())
	return m.next.Register(ctx, email, password)
}

func (m *metricsUserService) Login(ctx context.Context, email string, password string) (tokens dto.TokenPair, err error) {
	defer func(t time.Time) { m.record(ctx, metricMethodUserServiceLogin, t, err) }(time.Now())
	return m.next.Login(ctx, email, password)
}

func (m *metricsUserService) Refresh(ctx context.Context, refreshToken string) (tokens dto.TokenPair, err error) {
	defer func(t time.Time) { m.record(ctx, metricMethodUserServiceRefresh, t, err) }(time.Now())
	return m.next.Refresh(ctx, refreshToken)
}

func (m *metricsUserService) Me(ctx context.Context) (user dto.User, err error) {
	defer func(t time.Time) { m.record(ctx, metricMethodUserServiceMe, t, err) }(time.Now())
	return m.next.Me(ctx)
}

func (m *metricsUserService) Csrf(ctx context.Context) (resp dto.CsrfResponse, err error) {
	defer func(t time.Time) { m.record(ctx, metricMethodUserServiceCsrf, t, err) }(time.Now())
	return m.next.Csrf(ctx)
}
