// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/fiber/v2"
	"github.com/loki/todoservice/contracts"
)

type httpUserService struct {
	errorHandler ErrorHandler
	svc          *serverUserService
	base         contracts.UserService
}

func newUserService(svcUserService contracts.UserService) (srv *httpUserService) {
	srv = &httpUserService{
		base: svcUserService,
		svc:  newServerUserService(svcUserService),
	}
	return
}

func (http *httpUserService) Service() *serverUserService {
	return http.svc
}

func (http *httpUserService) WithMetrics(metrics *Metrics) *httpUserService {
	http.svc.WithMetrics(metrics)
	return http
}

func (http *httpUserService) WithErrorHandler(handler ErrorHandler) *httpUserService {
	http.errorHandler = handler
	return http
}

func (http *httpUserService) WithRedirect() *httpUserService {
	return http
}

func (http *httpUserService) SetRoutes(route *fiber.App) {
	route.Post("/auth/register", http.serveRegister)
	route.Post("/auth/login", http.serveLogin)
	route.Post("/auth/refresh", http.serveRefresh)
	route.Get("/auth/me", http.serveMe)
	route.Get("/auth/csrf", http.serveCsrf)
}
