// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.


package stream

type contextKey int

// KeyOverlay — context key для map[string]string HTTP overlay (headers/cookies/query/path) на WS session.
const KeyOverlay contextKey = 1
