#!/usr/bin/env bash
# Reference template — the actual bootstrap.sh is generated by
# microcode.generators.bootstrap from the sandbox.init section of platform.yaml.
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

apt-get update -qq
apt-get install -y -qq curl git ca-certificates python3 python3-pip

# node + bun
curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
apt-get install -y -qq nodejs
curl -fsSL https://bun.sh/install | bash

# subsystems
npm install -g loki-mode @skillkit/cli
npm install -g @anthropic-ai/claude-code

echo '[bootstrap] done.'
